# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Topo_dialog-cv.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(745, 559)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(340, 510, 391, 51))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 731, 141))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(60, 60, 581, 39))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cotaLabel = QtWidgets.QLabel(self.widget)
        self.cotaLabel.setObjectName("cotaLabel")
        self.horizontalLayout.addWidget(self.cotaLabel)
        self.cota = QtWidgets.QLineEdit(self.widget)
        self.cota.setObjectName("cota")
        self.horizontalLayout.addWidget(self.cota)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLabel = QtWidgets.QLabel(self.widget)
        self.horizontalLabel.setObjectName("horizontalLabel")
        self.horizontalLayout.addWidget(self.horizontalLabel)
        self.horizontal = QtWidgets.QLineEdit(self.widget)
        self.horizontal.setObjectName("horizontal")
        self.horizontalLayout.addWidget(self.horizontal)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 170, 731, 321))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(550, 230, 105, 39))
        self.pushButton.setObjectName("pushButton")
        self.widget1 = QtWidgets.QWidget(self.groupBox_2)
        self.widget1.setGeometry(QtCore.QRect(20, 240, 182, 39))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cotaLabel_4 = QtWidgets.QLabel(self.widget1)
        self.cotaLabel_4.setObjectName("cotaLabel_4")
        self.horizontalLayout_2.addWidget(self.cotaLabel_4)
        self.i2 = QtWidgets.QLineEdit(self.widget1)
        self.i2.setObjectName("i2")
        self.horizontalLayout_2.addWidget(self.i2)
        self.widget2 = QtWidgets.QWidget(self.groupBox_2)
        self.widget2.setGeometry(QtCore.QRect(20, 170, 182, 39))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cotaLabel_3 = QtWidgets.QLabel(self.widget2)
        self.cotaLabel_3.setObjectName("cotaLabel_3")
        self.horizontalLayout_3.addWidget(self.cotaLabel_3)
        self.i1 = QtWidgets.QLineEdit(self.widget2)
        self.i1.setObjectName("i1")
        self.horizontalLayout_3.addWidget(self.i1)
        self.widget3 = QtWidgets.QWidget(self.groupBox_2)
        self.widget3.setGeometry(QtCore.QRect(380, 120, 273, 39))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cotaLabel_7 = QtWidgets.QLabel(self.widget3)
        self.cotaLabel_7.setObjectName("cotaLabel_7")
        self.horizontalLayout_4.addWidget(self.cotaLabel_7)
        self.L = QtWidgets.QLineEdit(self.widget3)
        self.L.setObjectName("L")
        self.horizontalLayout_4.addWidget(self.L)
        self.widget4 = QtWidgets.QWidget(self.groupBox_2)
        self.widget4.setGeometry(QtCore.QRect(20, 70, 181, 39))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cotaLabel_2 = QtWidgets.QLabel(self.widget4)
        self.cotaLabel_2.setObjectName("cotaLabel_2")
        self.horizontalLayout_5.addWidget(self.cotaLabel_2)
        self.G = QtWidgets.QLineEdit(self.widget4)
        self.G.setObjectName("G")
        self.horizontalLayout_5.addWidget(self.G)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Modificar Curva Vertical"))
        self.groupBox.setTitle(_translate("Dialog", "Vértice"))
        self.cotaLabel.setText(_translate("Dialog", "Cota:"))
        self.horizontalLabel.setText(_translate("Dialog", "Horizontal111: "))
        self.groupBox_2.setTitle(_translate("Dialog", "Curva Vertical"))
        self.pushButton.setText(_translate("Dialog", "Ver Curva"))
        self.cotaLabel_4.setText(_translate("Dialog", "i2: "))
        self.cotaLabel_3.setText(_translate("Dialog", "i1: "))
        self.cotaLabel_7.setText(_translate("Dialog", "Comprimento: "))
        self.cotaLabel_2.setText(_translate("Dialog", "G: "))

