# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'curvaWidget.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(513, 246)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.k = QtWidgets.QLineEdit(Form)
        self.k.setEnabled(False)
        self.k.setMinimumSize(QtCore.QSize(150, 0))
        self.k.setMaximumSize(QtCore.QSize(150, 16777215))
        self.k.setReadOnly(True)
        self.k.setObjectName("k")
        self.horizontalLayout.addWidget(self.k)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.vmax = QtWidgets.QLineEdit(Form)
        self.vmax.setEnabled(False)
        self.vmax.setMinimumSize(QtCore.QSize(150, 0))
        self.vmax.setMaximumSize(QtCore.QSize(150, 16777215))
        self.vmax.setReadOnly(True)
        self.vmax.setObjectName("vmax")
        self.horizontalLayout.addWidget(self.vmax)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.nome = QtWidgets.QLabel(Form)
        self.nome.setObjectName("nome")
        self.horizontalLayout_4.addWidget(self.nome)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.raio = QtWidgets.QDoubleSpinBox(Form)
        self.raio.setDecimals(3)
        self.raio.setMaximum(100000.0)
        self.raio.setSingleStep(10.0)
        self.raio.setProperty("value", 160.0)
        self.raio.setObjectName("raio")
        self.horizontalLayout_2.addWidget(self.raio)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.deflexao = QtWidgets.QDoubleSpinBox(Form)
        self.deflexao.setDecimals(3)
        self.deflexao.setMinimum(-180.0)
        self.deflexao.setMaximum(180.0)
        self.deflexao.setSingleStep(5.0)
        self.deflexao.setObjectName("deflexao")
        self.horizontalLayout_2.addWidget(self.deflexao)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comprimento = QtWidgets.QDoubleSpinBox(Form)
        self.comprimento.setDecimals(3)
        self.comprimento.setMaximum(1000000.0)
        self.comprimento.setSingleStep(10.0)
        self.comprimento.setProperty("value", 60.0)
        self.comprimento.setObjectName("comprimento")
        self.horizontalLayout_3.addWidget(self.comprimento)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.T = QtWidgets.QDoubleSpinBox(Form)
        self.T.setDecimals(3)
        self.T.setMaximum(100000.0)
        self.T.setObjectName("T")
        self.horizontalLayout_3.addWidget(self.T)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 2, 3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setWhatsThis(_translate("Form", "<html><head/><body><p>Parâmetro da curva Espiral (K)</p></body></html>"))
        self.label.setText(_translate("Form", "Parâmetro:     "))
        self.k.setWhatsThis(_translate("Form", "<html><head/><body><p>Parâmetro da curva Espiral (K)</p></body></html>"))
        self.k.setText(_translate("Form", "0"))
        self.label_2.setWhatsThis(_translate("Form", "<html><head/><body><p>Velocidade Máxima para esse trecho de curva</p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("Form", "Vmax:  "))
        self.vmax.setWhatsThis(_translate("Form", "<html><head/><body><p>Velocidade Máxima para esse trecho de curva</p><p><br/></p></body></html>"))
        self.vmax.setText(_translate("Form", "0"))
        self.nome.setWhatsThis(_translate("Form", "<html><head/><body><p>Tipo de elemento a ser adicionado</p><p><br/></p></body></html>"))
        self.nome.setText(_translate("Form", "ERRO"))
        self.pushButton.setWhatsThis(_translate("Form", "<html><head/><body><p>Remover esse elemento ou curva</p><p><br/></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Excluir"))
        self.label_3.setWhatsThis(_translate("Form", "<html><head/><body><p>Raio da curva</p></body></html>"))
        self.label_3.setText(_translate("Form", "     Raio :            "))
        self.raio.setWhatsThis(_translate("Form", "<html><head/><body><p>Raio da curva</p></body></html>"))
        self.label_5.setWhatsThis(_translate("Form", "<html><head/><body><p>Deflexão da curva em graus</p><p><br/></p></body></html>"))
        self.label_5.setText(_translate("Form", "    Deflexão:     "))
        self.label_4.setWhatsThis(_translate("Form", "<html><head/><body><p>Desenvolvimento da curva (L)</p></body></html>"))
        self.label_4.setText(_translate("Form", "Comprimento: "))
        self.comprimento.setWhatsThis(_translate("Form", "<html><head/><body><p>Desenvolvimento da curva (L)</p></body></html>"))
        self.label_6.setText(_translate("Form", "Afastamento:"))
        self.checkBox.setText(_translate("Form", "Centralizar"))


