# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Topo_dialog-cv.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(901, 660)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 881, 241))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 932, 195))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setToolTip("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.uiestaca1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.uiestaca1.setToolTip("")
        self.uiestaca1.setObjectName("uiestaca1")
        self.horizontalLayout_8.addWidget(self.uiestaca1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setToolTip("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.cotaLabel_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cotaLabel_6.sizePolicy().hasHeightForWidth())
        self.cotaLabel_6.setSizePolicy(sizePolicy)
        self.cotaLabel_6.setToolTip("")
        self.cotaLabel_6.setLineWidth(1)
        self.cotaLabel_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cotaLabel_6.setWordWrap(False)
        self.cotaLabel_6.setObjectName("cotaLabel_6")
        self.horizontalLayout_14.addWidget(self.cotaLabel_6)
        self.uicota1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uicota1.sizePolicy().hasHeightForWidth())
        self.uicota1.setSizePolicy(sizePolicy)
        self.uicota1.setToolTip("")
        self.uicota1.setReadOnly(True)
        self.uicota1.setObjectName("uicota1")
        self.horizontalLayout_14.addWidget(self.uicota1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setToolTip("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setToolTip("")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.horizontalLayout_15.addLayout(self.verticalLayout_6)
        self.uihorizontal1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uihorizontal1.sizePolicy().hasHeightForWidth())
        self.uihorizontal1.setSizePolicy(sizePolicy)
        self.uihorizontal1.setToolTip("")
        self.uihorizontal1.setObjectName("uihorizontal1")
        self.horizontalLayout_15.addWidget(self.uihorizontal1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_16.setToolTip("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_19.addWidget(self.label_16)
        self.uiestaca = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.uiestaca.setObjectName("uiestaca")
        self.horizontalLayout_19.addWidget(self.uiestaca)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setToolTip("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_19.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cotaLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.cotaLabel.setToolTip("")
        self.cotaLabel.setObjectName("cotaLabel")
        self.horizontalLayout.addWidget(self.cotaLabel)
        self.uicota = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uicota.sizePolicy().hasHeightForWidth())
        self.uicota.setSizePolicy(sizePolicy)
        self.uicota.setToolTip("")
        self.uicota.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.uicota.setObjectName("uicota")
        self.horizontalLayout.addWidget(self.uicota)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem5 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_9.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.verticalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_20.addWidget(self.label_18)
        self.uiestaca2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.uiestaca2.setToolTip("")
        self.uiestaca2.setObjectName("uiestaca2")
        self.horizontalLayout_20.addWidget(self.uiestaca2)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_20.addWidget(self.label_17)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.cotaLabel_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cotaLabel_8.sizePolicy().hasHeightForWidth())
        self.cotaLabel_8.setSizePolicy(sizePolicy)
        self.cotaLabel_8.setToolTip("")
        self.cotaLabel_8.setObjectName("cotaLabel_8")
        self.horizontalLayout_16.addWidget(self.cotaLabel_8)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        self.uicota2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uicota2.sizePolicy().hasHeightForWidth())
        self.uicota2.setSizePolicy(sizePolicy)
        self.uicota2.setToolTip("")
        self.uicota2.setReadOnly(True)
        self.uicota2.setObjectName("uicota2")
        self.horizontalLayout_16.addWidget(self.uicota2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.horizontalLayout_17.addLayout(self.verticalLayout_8)
        self.uihorizontal2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uihorizontal2.sizePolicy().hasHeightForWidth())
        self.uihorizontal2.setSizePolicy(sizePolicy)
        self.uihorizontal2.setToolTip("")
        self.uihorizontal2.setObjectName("uihorizontal2")
        self.horizontalLayout_17.addWidget(self.uihorizontal2)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 310, 881, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 100, 221, 39))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cotaLabel_4 = QtWidgets.QLabel(self.layoutWidget)
        self.cotaLabel_4.setToolTip("")
        self.cotaLabel_4.setObjectName("cotaLabel_4")
        self.horizontalLayout_2.addWidget(self.cotaLabel_4)
        self.uii2 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uii2.sizePolicy().hasHeightForWidth())
        self.uii2.setSizePolicy(sizePolicy)
        self.uii2.setToolTip("")
        self.uii2.setReadOnly(True)
        self.uii2.setObjectName("uii2")
        self.horizontalLayout_2.addWidget(self.uii2)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 50, 221, 39))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cotaLabel_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.cotaLabel_3.setToolTip("")
        self.cotaLabel_3.setObjectName("cotaLabel_3")
        self.horizontalLayout_3.addWidget(self.cotaLabel_3)
        self.uii1 = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uii1.sizePolicy().hasHeightForWidth())
        self.uii1.setSizePolicy(sizePolicy)
        self.uii1.setToolTip("")
        self.uii1.setReadOnly(True)
        self.uii1.setObjectName("uii1")
        self.horizontalLayout_3.addWidget(self.uii1)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(320, 50, 227, 39))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cotaLabel_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.cotaLabel_7.setObjectName("cotaLabel_7")
        self.horizontalLayout_4.addWidget(self.cotaLabel_7)
        self.uiL = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiL.sizePolicy().hasHeightForWidth())
        self.uiL.setSizePolicy(sizePolicy)
        self.uiL.setObjectName("uiL")
        self.horizontalLayout_4.addWidget(self.uiL)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 150, 221, 39))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cotaLabel_2 = QtWidgets.QLabel(self.layoutWidget3)
        self.cotaLabel_2.setObjectName("cotaLabel_2")
        self.horizontalLayout_5.addWidget(self.cotaLabel_2)
        self.uiG = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiG.sizePolicy().hasHeightForWidth())
        self.uiG.setSizePolicy(sizePolicy)
        self.uiG.setReadOnly(True)
        self.uiG.setObjectName("uiG")
        self.horizontalLayout_5.addWidget(self.uiG)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 200, 221, 39))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.cotaLabel_9 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cotaLabel_9.sizePolicy().hasHeightForWidth())
        self.cotaLabel_9.setSizePolicy(sizePolicy)
        self.cotaLabel_9.setObjectName("cotaLabel_9")
        self.horizontalLayout_11.addWidget(self.cotaLabel_9)
        self.uiCurveType = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.uiCurveType.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiCurveType.sizePolicy().hasHeightForWidth())
        self.uiCurveType.setSizePolicy(sizePolicy)
        self.uiCurveType.setReadOnly(True)
        self.uiCurveType.setObjectName("uiCurveType")
        self.horizontalLayout_11.addWidget(self.uiCurveType)
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 250, 291, 39))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.cotaLabel_10 = QtWidgets.QLabel(self.layoutWidget_3)
        self.cotaLabel_10.setToolTip("")
        self.cotaLabel_10.setObjectName("cotaLabel_10")
        self.horizontalLayout_18.addWidget(self.cotaLabel_10)
        self.uif = QtWidgets.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uif.sizePolicy().hasHeightForWidth())
        self.uif.setSizePolicy(sizePolicy)
        self.uif.setToolTip("")
        self.uif.setReadOnly(True)
        self.uif.setObjectName("uif")
        self.horizontalLayout_18.addWidget(self.uif)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(320, 250, 221, 39))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.cotaLabel_19 = QtWidgets.QLabel(self.layoutWidget_4)
        self.cotaLabel_19.setObjectName("cotaLabel_19")
        self.horizontalLayout_27.addWidget(self.cotaLabel_19)
        self.uiLdes = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiLdes.sizePolicy().hasHeightForWidth())
        self.uiLdes.setSizePolicy(sizePolicy)
        self.uiLdes.setReadOnly(True)
        self.uiLdes.setObjectName("uiLdes")
        self.horizontalLayout_27.addWidget(self.uiLdes)
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(320, 100, 221, 39))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.cotaLabel_20 = QtWidgets.QLabel(self.layoutWidget_5)
        self.cotaLabel_20.setObjectName("cotaLabel_20")
        self.horizontalLayout_28.addWidget(self.cotaLabel_20)
        self.uiKmin = QtWidgets.QLineEdit(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiKmin.sizePolicy().hasHeightForWidth())
        self.uiKmin.setSizePolicy(sizePolicy)
        self.uiKmin.setReadOnly(True)
        self.uiKmin.setObjectName("uiKmin")
        self.horizontalLayout_28.addWidget(self.uiKmin)
        self.layoutWidget_6 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_6.setGeometry(QtCore.QRect(320, 150, 221, 39))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.cotaLabel_21 = QtWidgets.QLabel(self.layoutWidget_6)
        self.cotaLabel_21.setObjectName("cotaLabel_21")
        self.horizontalLayout_29.addWidget(self.cotaLabel_21)
        self.uiKdes = QtWidgets.QLineEdit(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiKdes.sizePolicy().hasHeightForWidth())
        self.uiKdes.setSizePolicy(sizePolicy)
        self.uiKdes.setReadOnly(True)
        self.uiKdes.setObjectName("uiKdes")
        self.horizontalLayout_29.addWidget(self.uiKdes)
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_7.setGeometry(QtCore.QRect(320, 200, 221, 39))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.cotaLabel_22 = QtWidgets.QLabel(self.layoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cotaLabel_22.sizePolicy().hasHeightForWidth())
        self.cotaLabel_22.setSizePolicy(sizePolicy)
        self.cotaLabel_22.setObjectName("cotaLabel_22")
        self.horizontalLayout_30.addWidget(self.cotaLabel_22)
        self.uiLmin = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.uiLmin.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiLmin.sizePolicy().hasHeightForWidth())
        self.uiLmin.setSizePolicy(sizePolicy)
        self.uiLmin.setReadOnly(True)
        self.uiLmin.setObjectName("uiLmin")
        self.horizontalLayout_30.addWidget(self.uiLmin)
        self.layoutWidget_8 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_8.setGeometry(QtCore.QRect(600, 50, 241, 39))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.cotaLabel_23 = QtWidgets.QLabel(self.layoutWidget_8)
        self.cotaLabel_23.setObjectName("cotaLabel_23")
        self.horizontalLayout_31.addWidget(self.cotaLabel_23)
        self.uiLutilizado = QtWidgets.QLineEdit(self.layoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiLutilizado.sizePolicy().hasHeightForWidth())
        self.uiLutilizado.setSizePolicy(sizePolicy)
        self.uiLutilizado.setObjectName("uiLutilizado")
        self.horizontalLayout_31.addWidget(self.uiLutilizado)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(750, 130, 91, 86))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.helpBtn = QtWidgets.QPushButton(self.layoutWidget4)
        self.helpBtn.setEnabled(True)
        self.helpBtn.setObjectName("helpBtn")
        self.verticalLayout_2.addWidget(self.helpBtn)
        self.viewCurveBtn = QtWidgets.QPushButton(self.layoutWidget4)
        self.viewCurveBtn.setObjectName("viewCurveBtn")
        self.verticalLayout_2.addWidget(self.viewCurveBtn)
        self.uiAlertaLb = QtWidgets.QLabel(self.groupBox_2)
        self.uiAlertaLb.setGeometry(QtCore.QRect(580, 250, 251, 23))
        self.uiAlertaLb.setText("")
        self.uiAlertaLb.setObjectName("uiAlertaLb")
        self.addCurveBtn = QtWidgets.QPushButton(Dialog)
        self.addCurveBtn.setGeometry(QtCore.QRect(350, 260, 171, 39))
        self.addCurveBtn.setObjectName("addCurveBtn")
        self.layoutWidget5 = QtWidgets.QWidget(Dialog)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 620, 881, 43))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.layoutWidget5)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.verticeCb = QtWidgets.QComboBox(self.layoutWidget5)
        self.verticeCb.setObjectName("verticeCb")
        self.horizontalLayout_6.addWidget(self.verticeCb)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.previousBtn = QtWidgets.QPushButton(self.layoutWidget5)
        self.previousBtn.setObjectName("previousBtn")
        self.horizontalLayout_6.addWidget(self.previousBtn)
        self.nextBtn = QtWidgets.QPushButton(self.layoutWidget5)
        self.nextBtn.setObjectName("nextBtn")
        self.horizontalLayout_6.addWidget(self.nextBtn)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.cancelBtn = QtWidgets.QPushButton(self.layoutWidget5)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_6.addWidget(self.cancelBtn)
        self.okBtn = QtWidgets.QPushButton(self.layoutWidget5)
        self.okBtn.setObjectName("okBtn")
        self.horizontalLayout_6.addWidget(self.okBtn)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.cotaLabel_6.setBuddy(self.uicota1)
        self.label_8.setBuddy(self.uihorizontal1)
        self.cotaLabel.setBuddy(self.uicota)
        self.cotaLabel_8.setBuddy(self.uicota2)
        self.label_11.setBuddy(self.uihorizontal2)
        self.label_12.setBuddy(self.uihorizontal2)
        self.cotaLabel_23.setBuddy(self.uiLutilizado)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.uicota, self.uihorizontal1)
        Dialog.setTabOrder(self.uihorizontal1, self.uihorizontal2)
        Dialog.setTabOrder(self.uihorizontal2, self.addCurveBtn)
        Dialog.setTabOrder(self.addCurveBtn, self.viewCurveBtn)
        Dialog.setTabOrder(self.viewCurveBtn, self.uiLutilizado)
        Dialog.setTabOrder(self.uiLutilizado, self.nextBtn)
        Dialog.setTabOrder(self.nextBtn, self.previousBtn)
        Dialog.setTabOrder(self.previousBtn, self.verticeCb)
        Dialog.setTabOrder(self.verticeCb, self.okBtn)
        Dialog.setTabOrder(self.okBtn, self.cancelBtn)
        Dialog.setTabOrder(self.cancelBtn, self.uicota1)
        Dialog.setTabOrder(self.uicota1, self.uicota2)
        Dialog.setTabOrder(self.uicota2, self.uii1)
        Dialog.setTabOrder(self.uii1, self.uii2)
        Dialog.setTabOrder(self.uii2, self.uiG)
        Dialog.setTabOrder(self.uiG, self.uiCurveType)
        Dialog.setTabOrder(self.uiCurveType, self.uif)
        Dialog.setTabOrder(self.uif, self.uiL)
        Dialog.setTabOrder(self.uiL, self.uiKmin)
        Dialog.setTabOrder(self.uiKmin, self.uiKdes)
        Dialog.setTabOrder(self.uiKdes, self.uiLmin)
        Dialog.setTabOrder(self.uiLmin, self.uiLdes)
        Dialog.setTabOrder(self.uiLdes, self.helpBtn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Modificar Curva Vertical"))
        self.groupBox.setTitle(_translate("Dialog", "Dados"))
        self.label_7.setText(_translate("Dialog", "Vértice 1 ("))
        self.uiestaca1.setText(_translate("Dialog", "TextLabel"))
        self.label_3.setText(_translate("Dialog", ")"))
        self.cotaLabel_6.setText(_translate("Dialog", "Co&ta:"))
        self.label_8.setText(_translate("Dialog", "&Distância"))
        self.label_9.setText(_translate("Dialog", "Horizontal"))
        self.label_16.setText(_translate("Dialog", "Vértice 2 ("))
        self.uiestaca.setText(_translate("Dialog", "TextLabel"))
        self.label_4.setText(_translate("Dialog", ")"))
        self.cotaLabel.setText(_translate("Dialog", "Co&ta:"))
        self.label_18.setText(_translate("Dialog", "Vértice 3 ("))
        self.uiestaca2.setText(_translate("Dialog", "TextLabel"))
        self.label_17.setText(_translate("Dialog", ")"))
        self.cotaLabel_8.setText(_translate("Dialog", "Cota:"))
        self.label_11.setText(_translate("Dialog", "Dist&ância"))
        self.label_12.setText(_translate("Dialog", "Hori&zontal"))
        self.groupBox_2.setTitle(_translate("Dialog", "Curva Vertical: Vértice 2"))
        self.cotaLabel_4.setText(_translate("Dialog", "i2(%): "))
        self.cotaLabel_3.setText(_translate("Dialog", "i1(%): "))
        self.cotaLabel_7.setText(_translate("Dialog", "L( 0,6.V): "))
        self.cotaLabel_2.setText(_translate("Dialog", "g(%): "))
        self.cotaLabel_9.setText(_translate("Dialog", "Curva: "))
        self.cotaLabel_10.setText(_translate("Dialog", "f:"))
        self.label_19.setText(_translate("Dialog", ". x²"))
        self.cotaLabel_19.setText(_translate("Dialog", "L des:"))
        self.cotaLabel_20.setText(_translate("Dialog", "Kmin:"))
        self.cotaLabel_21.setText(_translate("Dialog", "Kdes:"))
        self.cotaLabel_22.setText(_translate("Dialog", "L min:"))
        self.cotaLabel_23.setText(_translate("Dialog", "&Lutilizado"))
        self.helpBtn.setText(_translate("Dialog", "AJUDA"))
        self.viewCurveBtn.setText(_translate("Dialog", "Ver Curva"))
        self.addCurveBtn.setText(_translate("Dialog", "ADICIONAR CURVA"))
        self.label.setText(_translate("Dialog", "Vértice"))
        self.previousBtn.setText(_translate("Dialog", "Anterior"))
        self.nextBtn.setText(_translate("Dialog", "Próximo"))
        self.cancelBtn.setText(_translate("Dialog", "Cancel"))
        self.okBtn.setText(_translate("Dialog", "OK"))


