# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Topo_dialog_conf.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TopoDialogBase(object):
    def setupUi(self, TopoDialogBase):
        TopoDialogBase.setObjectName("TopoDialogBase")
        TopoDialogBase.setWindowModality(QtCore.Qt.WindowModal)
        TopoDialogBase.resize(911, 489)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TopoDialogBase.sizePolicy().hasHeightForWidth())
        TopoDialogBase.setSizePolicy(sizePolicy)
        TopoDialogBase.setAutoFillBackground(False)
        TopoDialogBase.setSizeGripEnabled(False)
        self.button_box = QtWidgets.QDialogButtonBox(TopoDialogBase)
        self.button_box.setEnabled(True)
        self.button_box.setGeometry(QtCore.QRect(720, 410, 176, 27))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.button_box.setObjectName("button_box")
        self.label = QtWidgets.QLabel(TopoDialogBase)
        self.label.setGeometry(QtCore.QRect(10, 10, 251, 17))
        self.label.setObjectName("label")
        self.txtCRS = QtWidgets.QLineEdit(TopoDialogBase)
        self.txtCRS.setGeometry(QtCore.QRect(10, 30, 391, 27))
        self.txtCRS.setObjectName("txtCRS")
        self.tableCRS = QtWidgets.QTableWidget(TopoDialogBase)
        self.tableCRS.setGeometry(QtCore.QRect(10, 60, 391, 371))
        self.tableCRS.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableCRS.setObjectName("tableCRS")
        self.tableCRS.setColumnCount(0)
        self.tableCRS.setRowCount(0)
        self.planoMin = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.planoMin.setGeometry(QtCore.QRect(630, 90, 111, 27))
        self.planoMin.setObjectName("planoMin")
        self.planoMax = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.planoMax.setGeometry(QtCore.QRect(780, 90, 111, 27))
        self.planoMax.setProperty("value", 8.0)
        self.planoMax.setObjectName("planoMax")
        self.onduladoMin = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.onduladoMin.setGeometry(QtCore.QRect(630, 140, 111, 27))
        self.onduladoMin.setProperty("value", 8.0)
        self.onduladoMin.setObjectName("onduladoMin")
        self.onduladoMax = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.onduladoMax.setGeometry(QtCore.QRect(780, 140, 111, 27))
        self.onduladoMax.setProperty("value", 20.0)
        self.onduladoMax.setObjectName("onduladoMax")
        self.montanhosoMin = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.montanhosoMin.setGeometry(QtCore.QRect(630, 190, 111, 27))
        self.montanhosoMin.setProperty("value", 20.0)
        self.montanhosoMin.setObjectName("montanhosoMin")
        self.montanhosoMax = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.montanhosoMax.setGeometry(QtCore.QRect(780, 190, 111, 27))
        self.montanhosoMax.setMaximum(100.0)
        self.montanhosoMax.setProperty("value", 100.0)
        self.montanhosoMax.setObjectName("montanhosoMax")
        self.label_2 = QtWidgets.QLabel(TopoDialogBase)
        self.label_2.setGeometry(QtCore.QRect(430, 90, 151, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(TopoDialogBase)
        self.label_3.setGeometry(QtCore.QRect(430, 140, 171, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(TopoDialogBase)
        self.label_4.setGeometry(QtCore.QRect(430, 190, 191, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(TopoDialogBase)
        self.label_5.setGeometry(QtCore.QRect(750, 90, 21, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(TopoDialogBase)
        self.label_6.setGeometry(QtCore.QRect(750, 140, 21, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(TopoDialogBase)
        self.label_7.setGeometry(QtCore.QRect(750, 190, 21, 20))
        self.label_7.setObjectName("label_7")
        self.groupBox = QtWidgets.QGroupBox(TopoDialogBase)
        self.groupBox.setGeometry(QtCore.QRect(420, 10, 471, 61))
        self.groupBox.setObjectName("groupBox")
        self.comboClasse = QtWidgets.QComboBox(self.groupBox)
        self.comboClasse.setGeometry(QtCore.QRect(10, 30, 451, 27))
        self.comboClasse.setAcceptDrops(False)
        self.comboClasse.setEditable(False)
        self.comboClasse.setObjectName("comboClasse")
        self.comboClasse.addItem("")
        self.comboClasse.addItem("")
        self.comboClasse.addItem("")
        self.comboClasse.addItem("")
        self.comboClasse.addItem("")
        self.comboClasse.addItem("")
        self.comboClasse.addItem("")
        self.comboClasse.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(TopoDialogBase)
        self.groupBox_2.setGeometry(QtCore.QRect(430, 320, 471, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboMap = QtWidgets.QComboBox(self.groupBox_2)
        self.comboMap.setGeometry(QtCore.QRect(10, 30, 451, 27))
        self.comboMap.setAcceptDrops(False)
        self.comboMap.setEditable(False)
        self.comboMap.setObjectName("comboMap")
        self.comboMap.addItem("")
        self.comboMap.addItem("")
        self.comboMap.addItem("")
        self.comboMap.addItem("")
        self.comboMap.addItem("")
        self.label_8 = QtWidgets.QLabel(TopoDialogBase)
        self.label_8.setGeometry(QtCore.QRect(10, 450, 881, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setIndent(-1)
        self.label_8.setObjectName("label_8")
        self.txtCSV = QtWidgets.QLineEdit(TopoDialogBase)
        self.txtCSV.setGeometry(QtCore.QRect(540, 230, 51, 27))
        self.txtCSV.setMaxLength(1)
        self.txtCSV.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCSV.setObjectName("txtCSV")
        self.label_9 = QtWidgets.QLabel(TopoDialogBase)
        self.label_9.setGeometry(QtCore.QRect(430, 230, 111, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(TopoDialogBase)
        self.label_10.setGeometry(QtCore.QRect(630, 230, 111, 20))
        self.label_10.setObjectName("label_10")
        self.comboUnits = QtWidgets.QComboBox(TopoDialogBase)
        self.comboUnits.setGeometry(QtCore.QRect(760, 230, 131, 27))
        self.comboUnits.setAcceptDrops(False)
        self.comboUnits.setEditable(False)
        self.comboUnits.setObjectName("comboUnits")
        self.comboUnits.addItem("")
        self.comboUnits.addItem("")
        self.comboUnits.addItem("")
        self.actionOpenFolderAction = QtWidgets.QAction(TopoDialogBase)
        self.actionOpenFolderAction.setObjectName("actionOpenFolderAction")

        self.retranslateUi(TopoDialogBase)
        self.button_box.accepted.connect(TopoDialogBase.accept)
        self.button_box.rejected.connect(TopoDialogBase.reject)
        self.txtCRS.textChanged['QString'].connect(self.tableCRS.update)
        QtCore.QMetaObject.connectSlotsByName(TopoDialogBase)

    def retranslateUi(self, TopoDialogBase):
        _translate = QtCore.QCoreApplication.translate
        TopoDialogBase.setWindowTitle(_translate("TopoDialogBase", "Topo"))
        self.label.setText(_translate("TopoDialogBase", "Sistema de coordenada do projeto:"))
        self.tableCRS.setSortingEnabled(True)
        self.label_2.setText(_translate("TopoDialogBase", "Taxa i para Plano(%)"))
        self.label_3.setText(_translate("TopoDialogBase", "Taxa i para Ondulado(%)"))
        self.label_4.setText(_translate("TopoDialogBase", "Taxa i para Montanhoso(%)"))
        self.label_5.setText(_translate("TopoDialogBase", "até"))
        self.label_6.setText(_translate("TopoDialogBase", "até"))
        self.label_7.setText(_translate("TopoDialogBase", "até"))
        self.groupBox.setTitle(_translate("TopoDialogBase", "Configurações do projeto:"))
        self.comboClasse.setItemText(0, _translate("TopoDialogBase", "Selecione a classe do projeto"))
        self.comboClasse.setItemText(1, _translate("TopoDialogBase", "0 - Via Expressa, controle total de acesso"))
        self.comboClasse.setItemText(2, _translate("TopoDialogBase", "1(A) - Pista dupla, controle parcial de acesso"))
        self.comboClasse.setItemText(3, _translate("TopoDialogBase", "1 (B) - Pista simples, controle parcial de acesso"))
        self.comboClasse.setItemText(4, _translate("TopoDialogBase", "2 - Pista simples"))
        self.comboClasse.setItemText(5, _translate("TopoDialogBase", "3 - Pista simples"))
        self.comboClasse.setItemText(6, _translate("TopoDialogBase", "4 (A) - Pista simples"))
        self.comboClasse.setItemText(7, _translate("TopoDialogBase", "4 (B) - Pista simples"))
        self.groupBox_2.setTitle(_translate("TopoDialogBase", "Servidor de mapas"))
        self.comboMap.setItemText(0, _translate("TopoDialogBase", "Selecione um servidor de mapas"))
        self.comboMap.setItemText(1, _translate("TopoDialogBase", "Google® Maps Satelite"))
        self.comboMap.setItemText(2, _translate("TopoDialogBase", "Google® Maps Street"))
        self.comboMap.setItemText(3, _translate("TopoDialogBase", "Bing® Maps Satelite"))
        self.comboMap.setItemText(4, _translate("TopoDialogBase", "Bing® Maps Street"))
        self.label_8.setText(_translate("TopoDialogBase", "[Nota Legal] As marcas Google® Maps e Bing® Maps são marcas comerciais pertencentes a Google Inc. e Microsoft Inc. respectivamente,\n"
" e são das mesmas os direitos do recurso de abertura de mapas. Tambem agradecemos ao projeto OpenLayers."))
        self.txtCSV.setText(_translate("TopoDialogBase", ";"))
        self.label_9.setText(_translate("TopoDialogBase", "Separador CSV"))
        self.label_10.setText(_translate("TopoDialogBase", "Padrão Medidas"))
        self.comboUnits.setItemText(0, _translate("TopoDialogBase", "Metros"))
        self.comboUnits.setItemText(1, _translate("TopoDialogBase", "Kilometros"))
        self.comboUnits.setItemText(2, _translate("TopoDialogBase", "Milimetros"))
        self.actionOpenFolderAction.setText(_translate("TopoDialogBase", "openFolderAction"))


