# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Topo_dialog_curva.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1009, 769)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.comboCurva = QtWidgets.QComboBox(Dialog)
        self.comboCurva.setObjectName("comboCurva")
        self.horizontalLayout_5.addWidget(self.comboCurva)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.comboElemento = QtWidgets.QComboBox(Dialog)
        self.comboElemento.setEnabled(True)
        self.comboElemento.setObjectName("comboElemento")
        self.comboElemento.addItem("")
        self.comboElemento.addItem("")
        self.horizontalLayout_5.addWidget(self.comboElemento)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 0, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout.addLayout(self.verticalLayout_11)
        self.btnClose = QtWidgets.QPushButton(Dialog)
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout.addWidget(self.btnClose)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout.addLayout(self.verticalLayout_10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.prev = QtWidgets.QPushButton(Dialog)
        self.prev.setEnabled(False)
        self.prev.setObjectName("prev")
        self.horizontalLayout_4.addWidget(self.prev)
        self.next = QtWidgets.QPushButton(Dialog)
        self.next.setEnabled(False)
        self.next.setObjectName("next")
        self.horizontalLayout_4.addWidget(self.next)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.btnAjuda = QtWidgets.QPushButton(Dialog)
        self.btnAjuda.setObjectName("btnAjuda")
        self.verticalLayout.addWidget(self.btnAjuda)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 2, 2, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 300))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboEstacaInicial = QtWidgets.QComboBox(self.groupBox)
        self.comboEstacaInicial.setEnabled(False)
        self.comboEstacaInicial.setObjectName("comboEstacaInicial")
        self.gridLayout.addWidget(self.comboEstacaInicial, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.txtEsteInicial = QtWidgets.QLineEdit(self.groupBox)
        self.txtEsteInicial.setEnabled(False)
        self.txtEsteInicial.setObjectName("txtEsteInicial")
        self.gridLayout.addWidget(self.txtEsteInicial, 4, 1, 1, 1)
        self.txtNorthInicial = QtWidgets.QLineEdit(self.groupBox)
        self.txtNorthInicial.setEnabled(False)
        self.txtNorthInicial.setObjectName("txtNorthInicial")
        self.gridLayout.addWidget(self.txtNorthInicial, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.txtNomeInicial = QtWidgets.QLineEdit(self.groupBox)
        self.txtNomeInicial.setEnabled(False)
        self.txtNomeInicial.setText("")
        self.txtNomeInicial.setObjectName("txtNomeInicial")
        self.gridLayout.addWidget(self.txtNomeInicial, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 300))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboEstacaFinal = QtWidgets.QComboBox(self.groupBox_2)
        self.comboEstacaFinal.setEnabled(False)
        self.comboEstacaFinal.setObjectName("comboEstacaFinal")
        self.gridLayout_2.addWidget(self.comboEstacaFinal, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.txtNomeFinal = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtNomeFinal.setEnabled(False)
        self.txtNomeFinal.setObjectName("txtNomeFinal")
        self.gridLayout_2.addWidget(self.txtNomeFinal, 2, 1, 1, 1)
        self.txtNorthFinal = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtNorthFinal.setEnabled(False)
        self.txtNorthFinal.setObjectName("txtNorthFinal")
        self.gridLayout_2.addWidget(self.txtNorthFinal, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.txtEsteFinal = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtEsteFinal.setEnabled(False)
        self.txtEsteFinal.setObjectName("txtEsteFinal")
        self.gridLayout_2.addWidget(self.txtEsteFinal, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 1, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnNew = QtWidgets.QPushButton(Dialog)
        self.btnNew.setObjectName("btnNew")
        self.verticalLayout_2.addWidget(self.btnNew)
        self.btnEditar = QtWidgets.QPushButton(Dialog)
        self.btnEditar.setObjectName("btnEditar")
        self.verticalLayout_2.addWidget(self.btnEditar)
        self.btnInsere = QtWidgets.QPushButton(Dialog)
        self.btnInsere.setEnabled(False)
        self.btnInsere.setObjectName("btnInsere")
        self.verticalLayout_2.addWidget(self.btnInsere)
        self.btnApagar = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnApagar.sizePolicy().hasHeightForWidth())
        self.btnApagar.setSizePolicy(sizePolicy)
        self.btnApagar.setObjectName("btnApagar")
        self.verticalLayout_2.addWidget(self.btnApagar)
        self.btnCancela = QtWidgets.QPushButton(Dialog)
        self.btnCancela.setEnabled(False)
        self.btnCancela.setObjectName("btnCancela")
        self.verticalLayout_2.addWidget(self.btnCancela)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 2, 2, 2, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_24 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_9.addWidget(self.label_24)
        self.txtDist = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDist.sizePolicy().hasHeightForWidth())
        self.txtDist.setSizePolicy(sizePolicy)
        self.txtDist.setObjectName("txtDist")
        self.verticalLayout_9.addWidget(self.txtDist)
        self.btnCalcular = QtWidgets.QPushButton(Dialog)
        self.btnCalcular.setObjectName("btnCalcular")
        self.verticalLayout_9.addWidget(self.btnCalcular)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem5)
        self.btnRelatorio = QtWidgets.QPushButton(Dialog)
        self.btnRelatorio.setEnabled(False)
        self.btnRelatorio.setObjectName("btnRelatorio")
        self.verticalLayout_9.addWidget(self.btnRelatorio)
        self.gridLayout_4.addLayout(self.verticalLayout_9, 4, 2, 1, 1)
        self.gDadosCurva = QtWidgets.QGroupBox(Dialog)
        self.gDadosCurva.setObjectName("gDadosCurva")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gDadosCurva)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txtVelocidade = QtWidgets.QDoubleSpinBox(self.gDadosCurva)
        self.txtVelocidade.setEnabled(False)
        self.txtVelocidade.setMaximum(400.0)
        self.txtVelocidade.setSingleStep(20.0)
        self.txtVelocidade.setObjectName("txtVelocidade")
        self.verticalLayout_3.addWidget(self.txtVelocidade)
        self.txtRUtilizado = QtWidgets.QDoubleSpinBox(self.gDadosCurva)
        self.txtRUtilizado.setEnabled(False)
        self.txtRUtilizado.setMaximum(10000.0)
        self.txtRUtilizado.setSingleStep(50.0)
        self.txtRUtilizado.setProperty("value", 500.0)
        self.txtRUtilizado.setObjectName("txtRUtilizado")
        self.verticalLayout_3.addWidget(self.txtRUtilizado)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txtFMAX = QtWidgets.QDoubleSpinBox(self.gDadosCurva)
        self.txtFMAX.setEnabled(False)
        self.txtFMAX.setMaximum(1.0)
        self.txtFMAX.setSingleStep(0.1)
        self.txtFMAX.setObjectName("txtFMAX")
        self.gridLayout_3.addWidget(self.txtFMAX, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.txtEMAX = QtWidgets.QDoubleSpinBox(self.gDadosCurva)
        self.txtEMAX.setEnabled(False)
        self.txtEMAX.setMaximum(1.0)
        self.txtEMAX.setSingleStep(0.01)
        self.txtEMAX.setProperty("value", 0.08)
        self.txtEMAX.setObjectName("txtEMAX")
        self.gridLayout_3.addWidget(self.txtEMAX, 0, 1, 1, 1)
        self.Ls = QtWidgets.QDoubleSpinBox(self.gDadosCurva)
        self.Ls.setEnabled(False)
        self.Ls.setMaximum(4000.0)
        self.Ls.setSingleStep(20.0)
        self.Ls.setObjectName("Ls")
        self.gridLayout_3.addWidget(self.Ls, 0, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 2, 1, 1)
        self.txtD = QtWidgets.QDoubleSpinBox(self.gDadosCurva)
        self.txtD.setEnabled(False)
        self.txtD.setMaximum(5000.0)
        self.txtD.setSingleStep(20.0)
        self.txtD.setObjectName("txtD")
        self.gridLayout_3.addWidget(self.txtD, 1, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 2, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_18 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_7.addWidget(self.label_18)
        self.label_26 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_7.addWidget(self.label_26)
        self.label_20 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_7.addWidget(self.label_20)
        self.label_23 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_7.addWidget(self.label_23)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.txtT = QtWidgets.QLineEdit(self.gDadosCurva)
        self.txtT.setEnabled(False)
        self.txtT.setText("")
        self.txtT.setObjectName("txtT")
        self.verticalLayout_8.addWidget(self.txtT)
        self.theta = QtWidgets.QLineEdit(self.gDadosCurva)
        self.theta.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.theta.sizePolicy().hasHeightForWidth())
        self.theta.setSizePolicy(sizePolicy)
        self.theta.setObjectName("theta")
        self.verticalLayout_8.addWidget(self.theta)
        self.txtG20 = QtWidgets.QLineEdit(self.gDadosCurva)
        self.txtG20.setEnabled(False)
        self.txtG20.setText("")
        self.txtG20.setObjectName("txtG20")
        self.verticalLayout_8.addWidget(self.txtG20)
        self.txtEPT = QtWidgets.QLineEdit(self.gDadosCurva)
        self.txtEPT.setEnabled(False)
        self.txtEPT.setText("")
        self.txtEPT.setObjectName("txtEPT")
        self.verticalLayout_8.addWidget(self.txtEPT)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 1, 2, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.label_17 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.label_21 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_5.addWidget(self.label_22)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.txtI = QtWidgets.QLineEdit(self.gDadosCurva)
        self.txtI.setEnabled(False)
        self.txtI.setText("")
        self.txtI.setObjectName("txtI")
        self.verticalLayout_6.addWidget(self.txtI)
        self.txtDelta = QtWidgets.QLineEdit(self.gDadosCurva)
        self.txtDelta.setEnabled(False)
        self.txtDelta.setText("")
        self.txtDelta.setObjectName("txtDelta")
        self.verticalLayout_6.addWidget(self.txtDelta)
        self.txtRMIN = QtWidgets.QLineEdit(self.gDadosCurva)
        self.txtRMIN.setEnabled(False)
        self.txtRMIN.setText("")
        self.txtRMIN.setObjectName("txtRMIN")
        self.verticalLayout_6.addWidget(self.txtRMIN)
        self.txtEPI = QtWidgets.QLineEdit(self.gDadosCurva)
        self.txtEPI.setEnabled(False)
        self.txtEPI.setText("")
        self.txtEPI.setObjectName("txtEPI")
        self.verticalLayout_6.addWidget(self.txtEPI)
        self.txtEPC = QtWidgets.QLineEdit(self.gDadosCurva)
        self.txtEPC.setEnabled(False)
        self.txtEPC.setText("")
        self.txtEPC.setObjectName("txtEPC")
        self.verticalLayout_6.addWidget(self.txtEPC)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 1, 0, 2, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 1, 3, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_29 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_29.setObjectName("label_29")
        self.gridLayout_9.addWidget(self.label_29, 2, 0, 1, 1)
        self.lsmin = QtWidgets.QLineEdit(self.gDadosCurva)
        self.lsmin.setEnabled(False)
        self.lsmin.setObjectName("lsmin")
        self.gridLayout_9.addWidget(self.lsmin, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_28.setObjectName("label_28")
        self.gridLayout_9.addWidget(self.label_28, 1, 0, 1, 1)
        self.lsmax = QtWidgets.QLineEdit(self.gDadosCurva)
        self.lsmax.setEnabled(False)
        self.lsmax.setObjectName("lsmax")
        self.gridLayout_9.addWidget(self.lsmax, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_27.setObjectName("label_27")
        self.gridLayout_9.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gDadosCurva)
        self.label_30.setObjectName("label_30")
        self.gridLayout_9.addWidget(self.label_30, 3, 0, 1, 1)
        self.xs = QtWidgets.QLineEdit(self.gDadosCurva)
        self.xs.setEnabled(False)
        self.xs.setObjectName("xs")
        self.gridLayout_9.addWidget(self.xs, 2, 1, 1, 1)
        self.ys = QtWidgets.QLineEdit(self.gDadosCurva)
        self.ys.setEnabled(False)
        self.ys.setObjectName("ys")
        self.gridLayout_9.addWidget(self.ys, 3, 1, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_9)
        self.gridLayout_5.addLayout(self.verticalLayout_12, 1, 4, 2, 1)
        self.gridLayout_4.addWidget(self.gDadosCurva, 3, 0, 2, 2)
        self.label_3.setBuddy(self.comboEstacaInicial)
        self.label_6.setBuddy(self.txtNorthInicial)
        self.label_7.setBuddy(self.txtEsteInicial)
        self.label_4.setBuddy(self.txtNomeInicial)
        self.label_5.setBuddy(self.comboEstacaFinal)
        self.label_8.setBuddy(self.txtNomeFinal)
        self.label_10.setBuddy(self.txtEsteFinal)
        self.label_9.setBuddy(self.txtNorthFinal)
        self.label_16.setBuddy(self.txtRUtilizado)
        self.label_13.setBuddy(self.txtEMAX)
        self.label_14.setBuddy(self.txtFMAX)

        self.retranslateUi(Dialog)
        self.btnClose.clicked.connect(Dialog.accept)
        self.prev.clicked.connect(Dialog.previousCurva)
        self.next.clicked.connect(Dialog.nextCurva)
        self.btnCancela.clicked.connect(Dialog.desabilitarControles)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Curvas Horizontais"))
        self.label.setText(_translate("Dialog", "Curva:"))
        self.label_2.setText(_translate("Dialog", "Tipo da Curva:"))
        self.comboElemento.setItemText(0, _translate("Dialog", "Circular Simples"))
        self.comboElemento.setItemText(1, _translate("Dialog", "Circular com Trasição Simétrica"))
        self.btnClose.setText(_translate("Dialog", "Fechar"))
        self.prev.setText(_translate("Dialog", "Anterior"))
        self.next.setText(_translate("Dialog", "Próxima"))
        self.btnAjuda.setText(_translate("Dialog", "?"))
        self.groupBox.setTitle(_translate("Dialog", "Ponto Inicial"))
        self.label_3.setText(_translate("Dialog", "E&staca:"))
        self.label_6.setText(_translate("Dialog", "&North:"))
        self.label_7.setText(_translate("Dialog", "Este:"))
        self.label_4.setText(_translate("Dialog", "&Nome:"))
        self.groupBox_2.setTitle(_translate("Dialog", "Ponto Final"))
        self.label_5.setText(_translate("Dialog", "Esta&ca:"))
        self.label_8.setText(_translate("Dialog", "No&me:"))
        self.label_10.setText(_translate("Dialog", "E&ste:"))
        self.label_9.setText(_translate("Dialog", "&North:"))
        self.btnNew.setText(_translate("Dialog", "Novo"))
        self.btnEditar.setText(_translate("Dialog", "Editar"))
        self.btnInsere.setText(_translate("Dialog", "Inserir"))
        self.btnApagar.setText(_translate("Dialog", "Apagar"))
        self.btnCancela.setText(_translate("Dialog", "Cancelar"))
        self.label_24.setText(_translate("Dialog", "Distância entre\n"
"estacas:"))
        self.btnCalcular.setText(_translate("Dialog", "Calcular"))
        self.btnRelatorio.setText(_translate("Dialog", "Desenhar"))
        self.gDadosCurva.setTitle(_translate("Dialog", "Dados da Curva"))
        self.label_15.setText(_translate("Dialog", "Velocidade:"))
        self.label_16.setText(_translate("Dialog", "Raio &Utilizado:"))
        self.label_13.setText(_translate("Dialog", "EMA&X:"))
        self.label_14.setText(_translate("Dialog", "FM&AX:"))
        self.label_25.setText(_translate("Dialog", "         Ls:"))
        self.label_19.setToolTip(_translate("Dialog", "<html><head/><body><p>Comprimento da curva circular (m)</p></body></html>"))
        self.label_19.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Comprimento da curva circular (m)</p></body></html>"))
        self.label_19.setText(_translate("Dialog", "         D:"))
        self.label_18.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Afastamento da curva (m)</p></body></html>"))
        self.label_18.setText(_translate("Dialog", "T:"))
        self.label_26.setToolTip(_translate("Dialog", "<html><head/><body><p>Angulo de defleção da transição</p></body></html>"))
        self.label_26.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Angulo de defleção da transição</p></body></html>"))
        self.label_26.setText(_translate("Dialog", "Theta:"))
        self.label_20.setText(_translate("Dialog", "G20:"))
        self.label_23.setText(_translate("Dialog", "E(PT):"))
        self.txtT.setToolTip(_translate("Dialog", "<html><head/><body><p>Afastamento da curva (m)</p></body></html>"))
        self.txtT.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Afastamento da curva (m)</p></body></html>"))
        self.theta.setToolTip(_translate("Dialog", "<html><head/><body><p>Angulo de defleção da transição</p></body></html>"))
        self.theta.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Angulo de defleção da transição</p></body></html>"))
        self.label_11.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Inclinação do trecho (%)</p></body></html>"))
        self.label_11.setText(_translate("Dialog", "I"))
        self.label_12.setToolTip(_translate("Dialog", "<html><head/><body><p>Deflexão da curva horizontal circular</p></body></html>"))
        self.label_12.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Deflexão da curva horizontal circular</p></body></html>"))
        self.label_12.setText(_translate("Dialog", "Delta:"))
        self.label_17.setToolTip(_translate("Dialog", "<html><head/><body><p>Raio Mínimo da curva circular (m)</p></body></html>"))
        self.label_17.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Raio Mínimo da curva circular (m)</p></body></html>"))
        self.label_17.setText(_translate("Dialog", "Raio Minimo:"))
        self.label_21.setText(_translate("Dialog", "E(PInovo):"))
        self.label_22.setText(_translate("Dialog", "E(PC):"))
        self.txtI.setToolTip(_translate("Dialog", "<html><head/><body><p>Inclinação do trecho (%)</p></body></html>"))
        self.txtI.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Inclinação do trecho (%)</p></body></html>"))
        self.txtDelta.setToolTip(_translate("Dialog", "<html><head/><body><p>Deflexão da curva horizontal circular</p></body></html>"))
        self.txtDelta.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Deflexão da curva horizontal circular</p></body></html>"))
        self.txtRMIN.setToolTip(_translate("Dialog", "<html><head/><body><p>Raio Mínimo da curva circular (m)</p></body></html>"))
        self.txtRMIN.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Raio Mínimo da curva circular (m)</p></body></html>"))
        self.label_29.setToolTip(_translate("Dialog", "<html><head/><body><p>Cooordenadas Xs e Ys do ponto entre curva de transição e circular.</p></body></html>"))
        self.label_29.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Cooordenadas Xs e Ys do ponto entre curva de transição e circular.</p></body></html>"))
        self.label_29.setText(_translate("Dialog", "Xs"))
        self.lsmin.setToolTip(_translate("Dialog", "<html><head/><body><p>Comprimento mínimo de transição (m)</p></body></html>"))
        self.lsmin.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Comprimento mínimo de transição (m)</p></body></html>"))
        self.label_28.setToolTip(_translate("Dialog", "<html><head/><body><p>Comprimento mácimo de transição (m)</p></body></html>"))
        self.label_28.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Comprimento mácimo de transição (m)</p></body></html>"))
        self.label_28.setText(_translate("Dialog", "Lsmax: "))
        self.lsmax.setToolTip(_translate("Dialog", "<html><head/><body><p>Comprimento mácimo de transição (m)</p></body></html>"))
        self.lsmax.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Comprimento mácimo de transição (m)</p></body></html>"))
        self.label_27.setToolTip(_translate("Dialog", "<html><head/><body><p>Comprimento mínimo de transição (m)</p></body></html>"))
        self.label_27.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Comprimento mínimo de transição (m)</p></body></html>"))
        self.label_27.setText(_translate("Dialog", "Lsmin: "))
        self.label_30.setToolTip(_translate("Dialog", "<html><head/><body><p>Cooordenadas Xs e Ys do ponto entre curva circular e de transição.</p></body></html>"))
        self.label_30.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Cooordenadas Xs e Ys do ponto entre curva circular e de transição.</p></body></html>"))
        self.label_30.setText(_translate("Dialog", "Ys"))
        self.xs.setToolTip(_translate("Dialog", "<html><head/><body><p>Cooordenadas Xs e Ys do ponto entre curva de transição e circular.</p></body></html>"))
        self.xs.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Cooordenadas Xs e Ys do ponto entre curva de transição e circular.</p></body></html>"))
        self.ys.setToolTip(_translate("Dialog", "<html><head/><body><p>Cooordenadas Xs e Ys do ponto entre curva circular e de transição.</p></body></html>"))
        self.ys.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Cooordenadas Xs e Ys do ponto entre curva circular e de transição.</p></body></html>"))


