# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Topo_dialog_conf.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TopoDialogBase(object):
    def setupUi(self, TopoDialogBase):
        TopoDialogBase.setObjectName("TopoDialogBase")
        TopoDialogBase.setWindowModality(QtCore.Qt.WindowModal)
        TopoDialogBase.resize(820, 653)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TopoDialogBase.sizePolicy().hasHeightForWidth())
        TopoDialogBase.setSizePolicy(sizePolicy)
        TopoDialogBase.setMinimumSize(QtCore.QSize(820, 300))
        TopoDialogBase.setAutoFillBackground(False)
        TopoDialogBase.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(TopoDialogBase)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_14 = QtWidgets.QLabel(TopoDialogBase)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.velProj = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.velProj.setMaximum(400.0)
        self.velProj.setProperty("value", 100.0)
        self.velProj.setObjectName("velProj")
        self.horizontalLayout_3.addWidget(self.velProj)
        self.label_8 = QtWidgets.QLabel(TopoDialogBase)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.gridLayout.addLayout(self.horizontalLayout_3, 12, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 2, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_emax = QtWidgets.QLabel(TopoDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_emax.sizePolicy().hasHeightForWidth())
        self.label_emax.setSizePolicy(sizePolicy)
        self.label_emax.setObjectName("label_emax")
        self.horizontalLayout_6.addWidget(self.label_emax)
        self.emax = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.emax.setDecimals(4)
        self.emax.setMaximum(1.0)
        self.emax.setSingleStep(0.01)
        self.emax.setProperty("value", 0.08)
        self.emax.setObjectName("emax")
        self.horizontalLayout_6.addWidget(self.emax)
        self.label_15 = QtWidgets.QLabel(TopoDialogBase)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.gridLayout.addLayout(self.horizontalLayout_6, 12, 2, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.onduladoMin = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.onduladoMin.setProperty("value", 8.0)
        self.onduladoMin.setObjectName("onduladoMin")
        self.horizontalLayout_9.addWidget(self.onduladoMin)
        self.label_6 = QtWidgets.QLabel(TopoDialogBase)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.onduladoMax = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.onduladoMax.setProperty("value", 20.0)
        self.onduladoMax.setObjectName("onduladoMax")
        self.horizontalLayout_9.addWidget(self.onduladoMax)
        self.gridLayout.addLayout(self.horizontalLayout_9, 9, 2, 1, 1)
        self.dbBuild = QtWidgets.QPushButton(TopoDialogBase)
        self.dbBuild.setObjectName("dbBuild")
        self.gridLayout.addWidget(self.dbBuild, 21, 1, 1, 1)
        self.comboMap = QtWidgets.QComboBox(TopoDialogBase)
        self.comboMap.setEnabled(False)
        self.comboMap.setObjectName("comboMap")
        self.gridLayout.addWidget(self.comboMap, 21, 2, 1, 1)
        self.interpol = QtWidgets.QCheckBox(TopoDialogBase)
        self.interpol.setChecked(True)
        self.interpol.setObjectName("interpol")
        self.gridLayout.addWidget(self.interpol, 15, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(TopoDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 9, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(TopoDialogBase)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.comboUnits = QtWidgets.QComboBox(TopoDialogBase)
        self.comboUnits.setAcceptDrops(False)
        self.comboUnits.setEditable(False)
        self.comboUnits.setObjectName("comboUnits")
        self.comboUnits.addItem("")
        self.comboUnits.addItem("")
        self.comboUnits.addItem("")
        self.horizontalLayout.addWidget(self.comboUnits)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 14, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(TopoDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.txtCSV = QtWidgets.QLineEdit(TopoDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCSV.sizePolicy().hasHeightForWidth())
        self.txtCSV.setSizePolicy(sizePolicy)
        self.txtCSV.setMaxLength(1)
        self.txtCSV.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCSV.setObjectName("txtCSV")
        self.horizontalLayout_2.addWidget(self.txtCSV)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 15, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(TopoDialogBase)
        self.label_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(TopoDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 10, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(TopoDialogBase)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox.setObjectName("groupBox")
        self.comboClasse = QtWidgets.QComboBox(self.groupBox)
        self.comboClasse.setGeometry(QtCore.QRect(20, 30, 421, 27))
        self.comboClasse.setAcceptDrops(False)
        self.comboClasse.setEditable(False)
        self.comboClasse.setObjectName("comboClasse")
        self.comboClasse.addItem("")
        self.comboClasse.addItem("")
        self.comboClasse.addItem("")
        self.comboClasse.addItem("")
        self.comboClasse.addItem("")
        self.comboClasse.addItem("")
        self.comboClasse.addItem("")
        self.comboClasse.addItem("")
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(TopoDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.estacas = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.estacas.setObjectName("estacas")
        self.horizontalLayout_5.addWidget(self.estacas)
        self.label_16 = QtWidgets.QLabel(TopoDialogBase)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.gridLayout.addLayout(self.horizontalLayout_5, 14, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 16, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.planoMin = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.planoMin.setObjectName("planoMin")
        self.horizontalLayout_8.addWidget(self.planoMin)
        self.label_5 = QtWidgets.QLabel(TopoDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.planoMax = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.planoMax.setProperty("value", 8.0)
        self.planoMax.setObjectName("planoMax")
        self.horizontalLayout_8.addWidget(self.planoMax)
        self.gridLayout.addLayout(self.horizontalLayout_8, 7, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_box = QtWidgets.QDialogButtonBox(TopoDialogBase)
        self.button_box.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_box.sizePolicy().hasHeightForWidth())
        self.button_box.setSizePolicy(sizePolicy)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.button_box.setObjectName("button_box")
        self.horizontalLayout_4.addWidget(self.button_box)
        self.gridLayout.addLayout(self.horizontalLayout_4, 23, 1, 1, 2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.montanhosoMin = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.montanhosoMin.setProperty("value", 20.0)
        self.montanhosoMin.setObjectName("montanhosoMin")
        self.horizontalLayout_10.addWidget(self.montanhosoMin)
        self.label_7 = QtWidgets.QLabel(TopoDialogBase)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.montanhosoMax = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.montanhosoMax.setMaximum(100.0)
        self.montanhosoMax.setProperty("value", 100.0)
        self.montanhosoMax.setObjectName("montanhosoMax")
        self.horizontalLayout_10.addWidget(self.montanhosoMax)
        self.gridLayout.addLayout(self.horizontalLayout_10, 10, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(TopoDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.transversal = QtWidgets.QDoubleSpinBox(TopoDialogBase)
        self.transversal.setMinimum(0.1)
        self.transversal.setMaximum(500.0)
        self.transversal.setProperty("value", 30.0)
        self.transversal.setObjectName("transversal")
        self.horizontalLayout_7.addWidget(self.transversal)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_7, 17, 1, 1, 2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtWidgets.QLabel(TopoDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.offsetSpinBox = QtWidgets.QSpinBox(TopoDialogBase)
        self.offsetSpinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.offsetSpinBox.setMinimum(2)
        self.offsetSpinBox.setProperty("value", 6)
        self.offsetSpinBox.setObjectName("offsetSpinBox")
        self.horizontalLayout_12.addWidget(self.offsetSpinBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_12, 19, 1, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 20, 1, 1, 1)
        self.actionOpenFolderAction = QtWidgets.QAction(TopoDialogBase)
        self.actionOpenFolderAction.setObjectName("actionOpenFolderAction")
        self.label_14.setBuddy(self.velProj)
        self.label_emax.setBuddy(self.emax)
        self.label_6.setBuddy(self.onduladoMax)
        self.label_3.setBuddy(self.onduladoMin)
        self.label_10.setBuddy(self.comboUnits)
        self.label_9.setBuddy(self.txtCSV)
        self.label_2.setBuddy(self.planoMin)
        self.label_4.setBuddy(self.montanhosoMin)
        self.label_11.setBuddy(self.estacas)
        self.label_5.setBuddy(self.planoMax)
        self.label_7.setBuddy(self.montanhosoMax)
        self.label_12.setBuddy(self.transversal)
        self.label_13.setBuddy(self.offsetSpinBox)

        self.retranslateUi(TopoDialogBase)
        self.button_box.accepted.connect(TopoDialogBase.accept)
        self.button_box.rejected.connect(TopoDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(TopoDialogBase)

    def retranslateUi(self, TopoDialogBase):
        _translate = QtCore.QCoreApplication.translate
        TopoDialogBase.setWindowTitle(_translate("TopoDialogBase", "Configurações do projeto"))
        self.label_14.setText(_translate("TopoDialogBase", "Velocidade &de projeto: "))
        self.label_8.setText(_translate("TopoDialogBase", "km/h"))
        self.label_emax.setText(_translate("TopoDialogBase", "  EMA&X: "))
        self.label_15.setText(_translate("TopoDialogBase", "m/m"))
        self.label_6.setText(_translate("TopoDialogBase", "&até"))
        self.dbBuild.setText(_translate("TopoDialogBase", "Reconstruir banco de dados"))
        self.interpol.setText(_translate("TopoDialogBase", "Interpolar Rasters?"))
        self.label_3.setText(_translate("TopoDialogBase", "Inc&linação para terreno ondulado (%)"))
        self.label_10.setText(_translate("TopoDialogBase", "&Unidades"))
        self.comboUnits.setItemText(0, _translate("TopoDialogBase", "Metros"))
        self.comboUnits.setItemText(1, _translate("TopoDialogBase", "Kilometros"))
        self.comboUnits.setItemText(2, _translate("TopoDialogBase", "Milimetros"))
        self.label_9.setText(_translate("TopoDialogBase", "Separador CSV"))
        self.txtCSV.setText(_translate("TopoDialogBase", ";"))
        self.label_2.setText(_translate("TopoDialogBase", "I&nclinação para terreno plano (%)"))
        self.label_4.setText(_translate("TopoDialogBase", "Inclinação para terreno &montanhoso (%)"))
        self.groupBox.setTitle(_translate("TopoDialogBase", "Classe do projeto:"))
        self.comboClasse.setItemText(0, _translate("TopoDialogBase", "Selecione a classe do projeto"))
        self.comboClasse.setItemText(1, _translate("TopoDialogBase", "0 - Via Expressa, controle total de acesso"))
        self.comboClasse.setItemText(2, _translate("TopoDialogBase", "1(A) - Pista dupla, controle parcial de acesso"))
        self.comboClasse.setItemText(3, _translate("TopoDialogBase", "1 (B) - Pista simples, controle parcial de acesso"))
        self.comboClasse.setItemText(4, _translate("TopoDialogBase", "2 - Pista simples"))
        self.comboClasse.setItemText(5, _translate("TopoDialogBase", "3 - Pista simples"))
        self.comboClasse.setItemText(6, _translate("TopoDialogBase", "4 (A) - Pista simples"))
        self.comboClasse.setItemText(7, _translate("TopoDialogBase", "4 (B) - Pista simples"))
        self.label_11.setText(_translate("TopoDialogBase", "Dist&ância entre estacas (m)"))
        self.label_5.setText(_translate("TopoDialogBase", "at&é"))
        self.label_7.setText(_translate("TopoDialogBase", "até"))
        self.label_12.setText(_translate("TopoDialogBase", "Espa&çamento transversal de cada lado (m)"))
        self.transversal.setWhatsThis(_translate("TopoDialogBase", "<html><head/><body><p>Espaçamento transversal em metros de cada lado da sessão transversal</p></body></html>"))
        self.label_13.setText(_translate("TopoDialogBase", "N&º de pontos                "))
        self.offsetSpinBox.setWhatsThis(_translate("TopoDialogBase", "<html><head/><body><p>Número de pontos para interpolar na sessão transversal, incluindo o ponto central</p><p><br/></p><p><br/></p></body></html>"))
        self.actionOpenFolderAction.setText(_translate("TopoDialogBase", "openFolderAction"))


