# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Topo_dialog_curva.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(775, 751)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_9.addWidget(self.label_24)
        self.txtDist = QtWidgets.QLineEdit(Dialog)
        self.txtDist.setObjectName("txtDist")
        self.verticalLayout_9.addWidget(self.txtDist)
        self.btnCalcular = QtWidgets.QPushButton(Dialog)
        self.btnCalcular.setObjectName("btnCalcular")
        self.verticalLayout_9.addWidget(self.btnCalcular)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.btnRelatorio = QtWidgets.QPushButton(Dialog)
        self.btnRelatorio.setObjectName("btnRelatorio")
        self.verticalLayout_9.addWidget(self.btnRelatorio)
        self.gridLayout_4.addLayout(self.verticalLayout_9, 5, 4, 1, 1)
        self.comboCurva = QtWidgets.QComboBox(Dialog)
        self.comboCurva.setObjectName("comboCurva")
        self.gridLayout_4.addWidget(self.comboCurva, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout.addLayout(self.verticalLayout_11)
        self.btnClose = QtWidgets.QPushButton(Dialog)
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout.addWidget(self.btnClose)
        self.btnCancela = QtWidgets.QPushButton(Dialog)
        self.btnCancela.setObjectName("btnCancela")
        self.verticalLayout.addWidget(self.btnCancela)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout.addLayout(self.verticalLayout_10)
        self.btnAjuda = QtWidgets.QPushButton(Dialog)
        self.btnAjuda.setObjectName("btnAjuda")
        self.verticalLayout.addWidget(self.btnAjuda)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 4, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnNew = QtWidgets.QPushButton(Dialog)
        self.btnNew.setObjectName("btnNew")
        self.verticalLayout_2.addWidget(self.btnNew)
        self.btnEditar = QtWidgets.QPushButton(Dialog)
        self.btnEditar.setObjectName("btnEditar")
        self.verticalLayout_2.addWidget(self.btnEditar)
        self.btnInsere = QtWidgets.QPushButton(Dialog)
        self.btnInsere.setEnabled(False)
        self.btnInsere.setObjectName("btnInsere")
        self.verticalLayout_2.addWidget(self.btnInsere)
        self.btnApagar = QtWidgets.QPushButton(Dialog)
        self.btnApagar.setObjectName("btnApagar")
        self.verticalLayout_2.addWidget(self.btnApagar)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 2, 4, 3, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 300))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 281, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboEstacaInicial = QtWidgets.QComboBox(self.layoutWidget)
        self.comboEstacaInicial.setEnabled(False)
        self.comboEstacaInicial.setObjectName("comboEstacaInicial")
        self.gridLayout.addWidget(self.comboEstacaInicial, 1, 1, 1, 1)
        self.txtNomeInicial = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtNomeInicial.setEnabled(False)
        self.txtNomeInicial.setText("")
        self.txtNomeInicial.setObjectName("txtNomeInicial")
        self.gridLayout.addWidget(self.txtNomeInicial, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.txtEsteInicial = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtEsteInicial.setEnabled(False)
        self.txtEsteInicial.setObjectName("txtEsteInicial")
        self.gridLayout.addWidget(self.txtEsteInicial, 5, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 1, 1, 1)
        self.txtNorthInicial = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtNorthInicial.setEnabled(False)
        self.txtNorthInicial.setObjectName("txtNorthInicial")
        self.gridLayout.addWidget(self.txtNorthInicial, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 2, 2)
        self.comboElemento = QtWidgets.QComboBox(Dialog)
        self.comboElemento.setEnabled(False)
        self.comboElemento.setObjectName("comboElemento")
        self.comboElemento.addItem("")
        self.comboElemento.addItem("")
        self.gridLayout_4.addWidget(self.comboElemento, 0, 3, 1, 1)
        self.gDadosCurva = QtWidgets.QGroupBox(Dialog)
        self.gDadosCurva.setObjectName("gDadosCurva")
        self.layoutWidget1 = QtWidgets.QWidget(self.gDadosCurva)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 213, 84))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txtVelocidade = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txtVelocidade.setEnabled(False)
        self.txtVelocidade.setObjectName("txtVelocidade")
        self.verticalLayout_3.addWidget(self.txtVelocidade)
        self.txtRUtilizado = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txtRUtilizado.setEnabled(False)
        self.txtRUtilizado.setObjectName("txtRUtilizado")
        self.verticalLayout_3.addWidget(self.txtRUtilizado)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.layoutWidget2 = QtWidgets.QWidget(self.gDadosCurva)
        self.layoutWidget2.setGeometry(QtCore.QRect(240, 30, 172, 82))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.txtEMAX = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txtEMAX.setEnabled(False)
        self.txtEMAX.setObjectName("txtEMAX")
        self.gridLayout_3.addWidget(self.txtEMAX, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.txtFMAX = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txtFMAX.setEnabled(False)
        self.txtFMAX.setText("")
        self.txtFMAX.setObjectName("txtFMAX")
        self.gridLayout_3.addWidget(self.txtFMAX, 1, 1, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.gDadosCurva)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 110, 205, 213))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_5.addWidget(self.label_22)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.txtI = QtWidgets.QLineEdit(self.layoutWidget3)
        self.txtI.setEnabled(False)
        self.txtI.setText("")
        self.txtI.setObjectName("txtI")
        self.verticalLayout_6.addWidget(self.txtI)
        self.txtDelta = QtWidgets.QLineEdit(self.layoutWidget3)
        self.txtDelta.setEnabled(False)
        self.txtDelta.setText("")
        self.txtDelta.setObjectName("txtDelta")
        self.verticalLayout_6.addWidget(self.txtDelta)
        self.txtRMIN = QtWidgets.QLineEdit(self.layoutWidget3)
        self.txtRMIN.setEnabled(False)
        self.txtRMIN.setText("")
        self.txtRMIN.setObjectName("txtRMIN")
        self.verticalLayout_6.addWidget(self.txtRMIN)
        self.txtEPI = QtWidgets.QLineEdit(self.layoutWidget3)
        self.txtEPI.setEnabled(False)
        self.txtEPI.setText("")
        self.txtEPI.setObjectName("txtEPI")
        self.verticalLayout_6.addWidget(self.txtEPI)
        self.txtEPC = QtWidgets.QLineEdit(self.layoutWidget3)
        self.txtEPC.setEnabled(False)
        self.txtEPC.setText("")
        self.txtEPC.setObjectName("txtEPC")
        self.verticalLayout_6.addWidget(self.txtEPC)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.layoutWidget4 = QtWidgets.QWidget(self.gDadosCurva)
        self.layoutWidget4.setGeometry(QtCore.QRect(240, 110, 175, 170))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_7.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_7.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_7.addWidget(self.label_20)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_7.addWidget(self.label_23)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.txtT = QtWidgets.QLineEdit(self.layoutWidget4)
        self.txtT.setEnabled(False)
        self.txtT.setText("")
        self.txtT.setObjectName("txtT")
        self.verticalLayout_8.addWidget(self.txtT)
        self.txtD = QtWidgets.QLineEdit(self.layoutWidget4)
        self.txtD.setEnabled(False)
        self.txtD.setText("")
        self.txtD.setObjectName("txtD")
        self.verticalLayout_8.addWidget(self.txtD)
        self.txtG20 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.txtG20.setEnabled(False)
        self.txtG20.setText("")
        self.txtG20.setObjectName("txtG20")
        self.verticalLayout_8.addWidget(self.txtG20)
        self.txtEPT = QtWidgets.QLineEdit(self.layoutWidget4)
        self.txtEPT.setEnabled(False)
        self.txtEPT.setText("")
        self.txtEPT.setObjectName("txtEPT")
        self.verticalLayout_8.addWidget(self.txtEPT)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.gridLayout_4.addWidget(self.gDadosCurva, 4, 0, 4, 4)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 300))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 20, 281, 231))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboEstacaFinal = QtWidgets.QComboBox(self.layoutWidget5)
        self.comboEstacaFinal.setEnabled(False)
        self.comboEstacaFinal.setObjectName("comboEstacaFinal")
        self.gridLayout_2.addWidget(self.comboEstacaFinal, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.txtNomeFinal = QtWidgets.QLineEdit(self.layoutWidget5)
        self.txtNomeFinal.setEnabled(False)
        self.txtNomeFinal.setObjectName("txtNomeFinal")
        self.gridLayout_2.addWidget(self.txtNomeFinal, 2, 1, 1, 1)
        self.txtNorthFinal = QtWidgets.QLineEdit(self.layoutWidget5)
        self.txtNorthFinal.setEnabled(False)
        self.txtNorthFinal.setObjectName("txtNorthFinal")
        self.gridLayout_2.addWidget(self.txtNorthFinal, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.txtEsteFinal = QtWidgets.QLineEdit(self.layoutWidget5)
        self.txtEsteFinal.setEnabled(False)
        self.txtEsteFinal.setObjectName("txtEsteFinal")
        self.gridLayout_2.addWidget(self.txtEsteFinal, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem5, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 2, 2, 2)

        self.retranslateUi(Dialog)
        self.btnClose.clicked.connect(Dialog.accept)
        self.btnCancela.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Curvas Horizontais Geradas por Vertices"))
        self.label_24.setText(_translate("Dialog", "Distância entre\n"
"estacas:"))
        self.btnCalcular.setText(_translate("Dialog", "Calcular"))
        self.btnRelatorio.setText(_translate("Dialog", "Relatorio \n"
" PDF"))
        self.btnClose.setText(_translate("Dialog", "Fechar"))
        self.btnCancela.setText(_translate("Dialog", "Cancelar"))
        self.btnAjuda.setText(_translate("Dialog", "?"))
        self.label.setText(_translate("Dialog", "Curva:"))
        self.btnNew.setText(_translate("Dialog", "Novo"))
        self.btnEditar.setText(_translate("Dialog", "Editar"))
        self.btnInsere.setText(_translate("Dialog", "Inserir"))
        self.btnApagar.setText(_translate("Dialog", "Apagar"))
        self.groupBox.setTitle(_translate("Dialog", "Ponto Inicial"))
        self.label_3.setText(_translate("Dialog", "Estaca:"))
        self.label_6.setText(_translate("Dialog", "North:"))
        self.label_7.setText(_translate("Dialog", "Este:"))
        self.label_4.setText(_translate("Dialog", "Nome:"))
        self.comboElemento.setItemText(0, _translate("Dialog", "Circular Simples"))
        self.comboElemento.setItemText(1, _translate("Dialog", "Circular de Entrada"))
        self.gDadosCurva.setTitle(_translate("Dialog", "Dados da Curva"))
        self.label_15.setText(_translate("Dialog", "Velocidade:"))
        self.label_16.setText(_translate("Dialog", "Raio Utilizado:"))
        self.txtVelocidade.setText(_translate("Dialog", "60"))
        self.txtRUtilizado.setText(_translate("Dialog", "600"))
        self.label_13.setText(_translate("Dialog", "EMAX:"))
        self.txtEMAX.setText(_translate("Dialog", "0.08"))
        self.label_14.setText(_translate("Dialog", "FMAX:"))
        self.label_11.setText(_translate("Dialog", "I:"))
        self.label_12.setText(_translate("Dialog", "Delta:"))
        self.label_17.setText(_translate("Dialog", "Raio Minimo:"))
        self.label_21.setText(_translate("Dialog", "E(PInovo):"))
        self.label_22.setText(_translate("Dialog", "E(PC):"))
        self.label_18.setText(_translate("Dialog", "T:"))
        self.label_19.setText(_translate("Dialog", "D:"))
        self.label_20.setText(_translate("Dialog", "G20:"))
        self.label_23.setText(_translate("Dialog", "E(PT):"))
        self.label_2.setText(_translate("Dialog", "Elemento:"))
        self.groupBox_2.setTitle(_translate("Dialog", "Ponto Final"))
        self.label_5.setText(_translate("Dialog", "Estaca:"))
        self.label_8.setText(_translate("Dialog", "Nome:"))
        self.label_10.setText(_translate("Dialog", "Este:"))
        self.label_9.setText(_translate("Dialog", "North:"))


